#ifndef TONEMAPPING_RS_HLSLI
#define TONEMAPPING_RS_HLSLI

#define TONEMAPPING_ROOT_SIG "RootFlags(CBV_SRV_UAV_HEAP_DIRECTLY_INDEXED |" \
	"DENY_AMPLIFICATION_SHADER_ROOT_ACCESS |"\
	"DENY_MESH_SHADER_ROOT_ACCESS |"\
	"DENY_HULL_SHADER_ROOT_ACCESS |"\
	"DENY_DOMAIN_SHADER_ROOT_ACCESS |"\
	"DENY_GEOMETRY_SHADER_ROOT_ACCESS |"\
	"DENY_PIXEL_SHADER_ROOT_ACCESS),"\
	"RootConstants(num32BitConstants=3, b0)"\

#endif // TONEMAPPING_RS_HLSLI
