#ifndef FXAA_RS_HLSLI
#define FXAA_RS_HLSLI

#define FXAA_ROOT_SIG "RootFlags(CBV_SRV_UAV_HEAP_DIRECTLY_INDEXED |" \
	"DENY_AMPLIFICATION_SHADER_ROOT_ACCESS |"\
	"DENY_MESH_SHADER_ROOT_ACCESS |"\
	"DENY_HULL_SHADER_ROOT_ACCESS |"\
	"DENY_DOMAIN_SHADER_ROOT_ACCESS |"\
	"DENY_GEOMETRY_SHADER_ROOT_ACCESS),"\
	"RootConstants(num32BitConstants=5, b0),"\
	"StaticSampler(s0, "\
		"addressU = TEXTURE_ADDRESS_WRAP,"\
		"addressV = TEXTURE_ADDRESS_WRAP,"\
		"filter = FILTER_MIN_MAG_MIP_LINEAR )"
	
#endif // FXAA_RS_HLSLI
