#ifndef BLOOM_RS_HLSLI
#define BLOOM_RS_HLSLI

#define BLOOM_RS "RootFlags(CBV_SRV_UAV_HEAP_DIRECTLY_INDEXED |"\
	"DENY_AMPLIFICATION_SHADER_ROOT_ACCESS |"\
	"DENY_MESH_SHADER_ROOT_ACCESS |"\
	"DENY_PIXEL_SHADER_ROOT_ACCESS |"\
	"DENY_HULL_SHADER_ROOT_ACCESS |"\
	"DENY_DOMAIN_SHADER_ROOT_ACCESS |"\
	"DENY_GEOMETRY_SHADER_ROOT_ACCESS),"\
	"RootConstants(num32BitConstants=8, b0),"\
	"StaticSampler(s0,"\
		"addressU = TEXTURE_ADDRESS_CLAMP,"\
		"addressV = TEXTURE_ADDRESS_CLAMP,"\
		"filter = FILTER_MIN_MAG_LINEAR_MIP_POINT )"\

#endif // BLOOM_RS_HLSLI
