#ifndef SKY_RS_HLSLI
#define SKY_RS_HLSLI

#define SKY_RS "RootFlags(CBV_SRV_UAV_HEAP_DIRECTLY_INDEXED |" \
	"DENY_HULL_SHADER_ROOT_ACCESS |"\
	"DENY_DOMAIN_SHADER_ROOT_ACCESS |"\
	"DENY_GEOMETRY_SHADER_ROOT_ACCESS |"\
	"DENY_AMPLIFICATION_SHADER_ROOT_ACCESS |"\
	"DENY_MESH_SHADER_ROOT_ACCESS),"\
	"RootConstants(num32BitConstants=16, b0), "\
	"RootConstants(num32BitConstants=48, b1), "\
	"StaticSampler(s0, "\
		"addressU = TEXTURE_ADDRESS_WRAP, "\
		"addressV = TEXTURE_ADDRESS_WRAP, "\
		"filter = FILTER_MIN_MAG_MIP_LINEAR )"

#endif // SKY_RS_HLSLI