#ifndef SSAO_RS
#define SSAO_RS

#define SSAO_ROOT_SIG "RootFlags(CBV_SRV_UAV_HEAP_DIRECTLY_INDEXED |"\
	"DENY_AMPLIFICATION_SHADER_ROOT_ACCESS |"\
	"DENY_MESH_SHADER_ROOT_ACCESS |"\
	"DENY_HULL_SHADER_ROOT_ACCESS |"\
	"DENY_DOMAIN_SHADER_ROOT_ACCESS |"\
	"DENY_GEOMETRY_SHADER_ROOT_ACCESS),"\
	"CBV(b0, space=0),"\
	"StaticSampler(s0, "\
		"addressU = TEXTURE_ADDRESS_BORDER, "\
		"addressV = TEXTURE_ADDRESS_BORDER, "\
		"filter = FILTER_MIN_MAG_MIP_LINEAR ),"\
	"StaticSampler(s1, "\
		"addressU = TEXTURE_ADDRESS_WRAP, "\
		"addressV = TEXTURE_ADDRESS_WRAP, "\
		"filter = FILTER_MIN_MAG_MIP_POINT )"

#endif // SSAO_RS
